name: Survey Automation - Every 6 Hours

on:
  schedule:
    # Runs every 6 hours: 00:00, 06:00, 12:00, 18:00 UTC
    - cron: '0 */6 * * *'
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering

jobs:
  submit-surveys:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run Survey Automation
      run: node api/cron-submit.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Log completion
      run: |
        echo "✅ Survey automation completed at $(date)"
        echo "🌍 Next run in 6 hours"
